### ISSUE TITLE
androidX支持库

### ISSUE THREAD

**Issue by for7GG** [LidongWen/MultiTypeAdapter#5]
什么时候支持下androidX类库呢

**Comment by chenxukunyx** [comment]
尽快支持一下AndroidX吧

**Comment by LidongWen** [comment]
各位抱歉 作者已转JAVA；可能不更新了；  
关于MultiTypeAdapter 我记的应该是没有指定版本的，AndroidX库应该是支持的吧？ 难道X库中类做了很大的改造吗？
![image](https://user-images.githubusercontent.com/16850429/53383262-f988d680-39b1-11e9-8b9e-f55b3eaffe57.png)

**Comment by for7GG** [comment]
可以在as中自行设置
